import "./globals.css";
import { getSession } from "@/lib/server";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  const prev = (await session.get("counter")) ?? 0;
  await session.set("counter", prev + 1);
  // todo: セッションを画面上で表示できるようにhooksを用意
  console.log("[[prev]]", prev);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
